import Head from 'next/head'
import { useState } from 'react';
import Header from "../components/header";
import { getEthAccountBalance } from '../utils/services';
import { weiToEth } from '../utils/helper';


const Balance = () => {

    const [address, setAddress] = useState(undefined);
    const [waiting, isWaiting] = useState(false);
    const [error, setError] = useState(null);


    const getBalance = async (e) => {
        e.preventDefault();
        const funds = await getEthAccountBalance(address);
        const ethFunds = weiToEth(funds);
    }

    function handleInputChange(e) {
        setAddress(e.target.value);
    }
    
    return (
        <>
            <Head>
                <title>Account Balance</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className="flex justify-center text-center">

                <form 
                    onSubmit={getBalance} 
                    className='grid sm:grid-cols-10 gap-4 ustify-center my-8 w-4/5 shadow p-4'
                >
                    <label 
                        className='sm:col-span-10 text-lg text-gray-700 font-bold mb-2' 
                        htmlFor='address'
                    >
                        Address
                    </label>
                    <input 
                        className='sm:col-span-8 bg-gray-200 p-2 rounded' 
                        type="text" 
                        id='address' 
                        placeholder='Address'
                        onChange={handleInputChange}
                        value={address}
                    />
                    <button 
                        className='disabled:opacity-25 hover:bg-blue-800 sm:col-span-2 bg-blue-500 rounded py-2 px-2 text-white font-bold' 
                        type="submit"
                        disabled={
                            !address || waiting
                        }
                    >
                        Search
                    </button>
                </form>

            </main>
            
        </>
    )
}

export default Balance;